import NavBar from './components/navBar';
import './globals.css';
import type { Metadata } from 'next';
import Footer from './components/footer'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
