import NavBar from './components/navBar';
import './globals.css';
import type { Metadata } from 'next';
import Footer from './components/footer'
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: 'Canvas Lancer',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {children}
                <Toaster position="top-right" reverseOrder={false} />
        <Footer/>
      </body>
    </html>
  );
}
